/**
 * Regenerate `packages/shared/src/skills/seed-content.ts` from `docs/skills/`.
 *
 * The seed bodies are embedded as string literals rather than read from `docs/` at
 * runtime, because a packaged app does not ship the repository's `docs/` tree — reading
 * from it would work in development and fail silently in a build. That leaves two
 * copies of the same text, which used to be kept in step by hand. This script is what
 * makes `docs/skills/` the source of truth in fact rather than only in a comment, and
 * `seed-content.test.ts` fails if the two ever drift.
 *
 * Run with `bun run sync:skills`.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** Where the editable skill sources live. */
const SKILLS_DIR = join(import.meta.dirname, '..', 'docs', 'skills')

/** The file this script writes. */
const OUTPUT = join(
  import.meta.dirname,
  '..',
  'packages',
  'shared',
  'src',
  'skills',
  'seed-content.ts'
)

/**
 * Escape text for a TypeScript template literal.
 * @param value - The raw file content
 * @returns The content, safe between backticks
 */
function templateLiteral(value: string): string {
  return '`' + value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`'
}

const names = readdirSync(SKILLS_DIR, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort()

const skills = names.map((name) => ({
  name,
  content: readFileSync(join(SKILLS_DIR, name, 'SKILL.md'), 'utf-8')
}))

const header = `/**
 * The runtime skills a fresh install starts with.
 *
 * \`SkillsLoader\` reads \`~/.keylimepi/skills\`, and for a long time nothing ever wrote it.
 * The copies under \`docs/skills/\` were exactly that — copies, with no install step — so
 * on any machine where they had not been placed by hand the agent ran with **no skills
 * at all**. That is worse than it sounds: \`working-notes\` is the \`NOTES.md\` convention
 * the post-compaction nudge in \`agent/session.ts\` explicitly tells the model to go and
 * read, so the one mechanism built to survive a summarized conversation was never taught
 * to the model that needed it.
 *
 * The content is embedded rather than copied from \`docs/\` at runtime, following
 * \`DEFAULT_GITIGNORE\` in \`../apps/templates.ts\`. A packaged app does not ship the
 * repository's \`docs/\` tree, so reading from it would work in development and fail
 * silently in a build — the failure mode this module exists to end.
 *
 * **Generated by \`scripts/generate-seed-content.ts\` — do not edit by hand.** Edit
 * \`docs/skills/<name>/SKILL.md\` and run \`bun run sync:skills\`.
 */

/**
 * One seeded skill.
 */
export interface SeedSkill {
  /** Directory name under the skills root, matching the skill's frontmatter name. */
  name: string
  /** The complete \`SKILL.md\`, frontmatter included. */
  content: string
}

/**
 * The skills written on first run.
 */
export const SEED_SKILLS: SeedSkill[] = [
`

const body = skills
  .map((skill) => `  {\n    name: ${JSON.stringify(skill.name)},\n    content: ${templateLiteral(skill.content)}\n  }`)
  .join(',\n')

writeFileSync(OUTPUT, `${header}${body}\n]\n`)
console.log(`seed-content.ts: ${skills.length} skills (${skills.map((s) => s.name).join(', ')})`)
